### PR TITLE
Default True Boolean prop bug fix

### LINKED ISSUE #46: Booleans that default to true show up wrong in vue code example
In the live code example under the props playground, the JS example works, but the Vue template example does not.

### PR DESCRIPTION
**Pull request by TheJaredWilcurt**
Closes #46

### CODE REVIEW

File: lib/components/ComponentDemo.vue [hunk 1]
```diff
@@ -201,7 +201,19 @@ export default {
...
+        const propDefault = this.playgroundProps?.[propName]?.default;
+        const modelValue = this.propsToDemo?.[propName]?.props?.modelValue;
+
+        if (propDefault === undefined && modelValue === undefined) {
+          this.demoProps[propName] = undefined;
+        } else {
+          if (propDefault !== undefined) {
+            this.demoProps[propName] = propDefault;
+          }
+          if (modelValue !== undefined) {
```
Comment (TheJaredWilcurt) [inline lib/components/ComponentDemo.vue:213]:
```suggestion
          // Intentionally not using else if
          if (modelValue !== undefined) {
```
